version: '3.8'

services:

  api-gateway:
    container_name: api-gateway
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    environment:
      AUTH_JWK_URI: http://auth-service:8015/oauth2/jwks
      AUTH_SERVICE_URI: http://auth-service:8015
      ACCOUNT_SERVICE_URI: http://account-service:8011
      AGENCY_SERVICE_URI: http://agency-service:8012
      USER_SERVICE_URI: http://user-service:8013
      TRANSACTION_SERVICE_URI: http://transaction-service:8014
    networks:
      - platform-network

networks:
  platform-network:
    external: true
